language: csharp
solution: MySqlQueryBuilder.sln
mono: none
dotnet: 2.1
script:
 - dotnet restore
install:
  - apt install nuget
  - nuget restore MySqlQueryBuilder.sln
  - nuget install xunit.runners -Version 2.3.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MySqlQueryBuilder.sln
  - mono ./testrunner/xunit.runners.2.3.1/tools/xunit.console.clr4.exe ./MySqlQueryBuilderTest/bin/Debug/netcoreapp2.1/MySqlQueryBuilderTest.dll