language: csharp
#sudo: required 
dist: xenial
solution: MySqlQueryBuilder.sln
mono: none
dotnet: 2.1
script:
 - dotnet restore
install:
  - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
  - sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/prod.list
  - sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
  - sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
  - sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
  #- sudo apt install nuget
  #- nuget restore MySqlQueryBuilder.sln
  #- dotnet restore
  #- dotnet add MySqlQueryBuilderTest package xunit.runner.console --version 2.3.1
  #- dotnet test MySqlQueryBuilderTest/
  #- nuget install xunit.runners -Version 2.4.0 -OutputDirectory testrunner
before_script:
  - dotnet restore
  - mysql -e 'create database mysql_query_test';
script:
  - dotnet test MySqlQueryBuilderTest/
 # - xbuild /p:Configuration=Release MySqlQueryBuilder.sln
 # - mono ./testrunner/xunit.runners.2.4.0/tools/xunit.console.clr4.exe ./MySqlQueryBuilderTest/bin/Debug/netcoreapp2.1/MySqlQueryBuilderTest.dll