language: csharp
#sudo: required 
dist: xenial
solution: MySqlQueryBuilder.sln
mono: none
dotnet: 2.1
script:
 - dotnet restore
install:
  - wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
  - sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
  - wget -q https://packages.microsoft.com/config/ubuntu/16.04/prod.list
  - sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
  - sudo chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg
  - sudo chown root:root /etc/apt/sources.list.d/microsoft-prod.list
  - sudo apt install nuget
  - nuget restore MySqlQueryBuilder.sln
  - nuget install xunit.runners -Version 2.3.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MySqlQueryBuilder.sln
  - mono ./testrunner/xunit.runners.2.3.1/tools/xunit.console.clr4.exe ./MySqlQueryBuilderTest/bin/Debug/netcoreapp2.1/MySqlQueryBuilderTest.dll