# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - production

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  
# enable service required for build/tests
services:
  - mysql

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

build:
  parallel: true
  project: MySqlQueryBuilder.sln

before_build:
  - dotnet restore

before_test:
  - SET PATH=%PATH%;C:\Program Files\MySQL\MySQL Server 5.7\bin
  
  # Reset Database password (MySQL 5.7.5)
  - mysql -u root --password=Password12! -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD(''); FLUSH PRIVILEGES;"
  
  # Reset Database password (MySQL 5.7.6+)
  #- mysql -u root --password=Password12! -e "ALTER USER 'root'@'localhost' IDENTIFIED BY ''; FLUSH PRIVILEGES;"
  
  # Create test database
  - mysql -u root -e "create database mysql_query_test CHARACTER SET utf8 COLLATE utf8_unicode_ci;"

# Run custom scripts instead of automatic tests
test_script:
  - dotnet test MySqlQueryBuilderTest/
