# version format
version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master
    - production

  # blacklist
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Release

# enable service required for build/tests
services:
  - mysql

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch
  - echo This is batch

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  parallel: true
  project: MySqlQueryBuilder.sln

# scripts to run before build
before_build:
  - dotnet restore

before_test:
  - "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -u root -e "create database mysql_query_test CHARACTER SET utf8 COLLATE utf8_unicode_ci;"

# to run your custom scripts instead of automatic tests
test_script:
  - dotnet test MySqlQueryBuilderTest/
